export const internalDictionaryEn = {
  nav: { analytics: "Analytics", cases: "Cases", operations: "Operations", privacy: "Privacy", signOut: "Sign out" },
  common: { app: "KommuneFlow AI", missing: "Missing", none: "None", unknown: "Unknown", unassigned: "Unassigned", last24h: "last 24h", language: "Language" },
  login: { title: "Internal login", intro: "Use a seeded municipal employee account to access the case dashboard.", email: "Email", password: "Password", signIn: "Sign in", signingIn: "Signing in...", invalid: "Invalid email or password." },
  cases: { title: "Case dashboard", status: "Status", case: "Case", department: "Department", created: "Created", loadError: "Could not load cases.", empty: "No cases found.", back: "Back to cases", loading: "Loading case...", citizen: "Citizen", urgency: "Urgency", address: "Address enrichment", originalAddress: "Original address", normalizedAddress: "Normalized address", municipality: "Municipality", postalCode: "Postal code", coordinates: "Coordinates", validation: "Validation", notAvailable: "Not available", noAddress: "No address was submitted with this case.", updateStatus: "Update status", notes: "Internal notes", addNote: "Add note", loadCaseError: "Could not load case.", loadDocumentsError: "Could not load documents.", loadAiError: "Could not load AI triage.", updateStatusError: "Could not update status.", uploadError: "Could not upload document.", runAiError: "Could not run AI triage.", reviewAiError: "Could not review AI triage." },
  ai: { title: "AI triage", generate: "Generate suggestion", notice: "AI suggestions are decision support only. A human case worker must review and approve any category, department, or urgency change.", empty: "No AI suggestion generated for this case.", failed: "AI triage failed", category: "Category", department: "Department", urgency: "Urgency", confidence: "Confidence", summary: "Summary", missingInfo: "Missing information", reason: "Reason", humanReview: "Human review", departmentSlug: "Department slug", accept: "Accept suggestion", saveCorrection: "Save correction" },
  documents: { title: "Documents", help: "PDF, PNG, JPG up to 10 MB", upload: "Upload", sensitiveDocument: "Sensitive document", sensitive: "Sensitive", empty: "No documents uploaded.", download: "Download", uploadedBy: "Uploaded by" },
  analytics: { title: "Analytics", from: "From", to: "To", aggregate: "Aggregate", aggregating: "Aggregating...", loadError: "Could not load analytics.", aggregateError: "Could not aggregate analytics.", cases: "Cases", aiReviews: "AI reviews", aiCorrections: "AI corrections", aiCorrectionRate: "AI correction rate", aiAcceptanceRate: "AI acceptance rate", aiTriageFailures: "AI triage failures", waitingForCitizen: "Waiting for citizen", minutesSaved: "Estimated minutes saved", avgTriage: "Avg. time to triage", medianTriage: "Median time to triage", avgClose: "Avg. time to close", medianClose: "Median time to close", per1000: "Cases per 1,000 inhabitants", population: "Population basis", ssbYear: "SSB year", ssbStatus: "SSB status", effectTitle: "Effect measurement", effectText: "Estimated manual time saved is a documented estimate, not an exact measurement.", lastRebuild: "Last rebuild", assumption: "Assumption", acceptedSave: "accepted AI suggestions save", correctedSave: "corrected AI suggestions save", minutes: "minutes", ssbTitle: "SSB enrichment", ssbText: "Population data from Statistics Norway table 07459 is used to calculate cases per 1,000 inhabitants.", source: "Source", ssbMissing: "SSB population data is missing for this range. Import municipality statistics and rebuild analytics to enable normalized metrics.", ssbStale: "SSB population data is stale. Re-import municipality statistics and rebuild analytics before using normalized metrics in decisions.", imported: "Last imported", byDepartment: "Case volume by department", byCategory: "Case volume by category", byStatus: "Case volume by status", daily: "Daily volume", noData: "No data.", noDaily: "No aggregated analytics for this range.", aiCorrection: "AI correction", aiFailure: "AI failure", minSaved: "min saved" },
  operations: { title: "Operations", health: "API health", readiness: "Readiness", backup: "Backup", readinessChecks: "Readiness checks", integrations: "Integrations", kartverketLookups: "Kartverket lookups", kartverketFailures: "Kartverket failures", kartverketLatency: "Kartverket avg latency", ssbImport: "SSB import", failedLogins: "Failed logins", permissionDenied: "Permission denied", crossTenant: "Cross-tenant attempts", rateLimit: "Rate limit blocks", aiRequests: "AI triage requests", aiFailures: "AI triage failures", uploadFailures: "Document upload failures", jobs: "Background jobs", analyticsRebuild: "Analytics rebuild", retention: "Retention cleanup", apiErrors: "API errors", apiErrors24h: "API errors last 24h", aiLatency: "AI average latency", loadMetricsError: "Could not load operations metrics.", loadDashboardError: "Could not load operations dashboard." },
  privacy: { title: "Privacy", statusTitle: "Privacy status", capabilities: "Capabilities", exportTitle: "Citizen data export", email: "Email", citizenProfileId: "Citizen profile ID", export: "Export data", anonymizeTitle: "Anonymize citizen profile", anonymize: "Anonymize", retentionTitle: "Retention cleanup", retentionPolicyTitle: "Retention policy", closedCaseRetentionDays: "Closed case retention days", deletedDocumentRetentionDays: "Deleted document retention days", auditEventRetentionDays: "Audit event retention days", analyticsRetentionDays: "Analytics retention days", savePolicy: "Save policy", dryRun: "Dry run", cleanup: "Confirm cleanup", loading: "Working...", loadingStatus: "Loading privacy status...", error: "Privacy action failed.", forbidden: "You do not have permission to perform this privacy action.", result: "Result", readOnly: "Auditors can inspect privacy status but cannot run export, anonymization, or cleanup actions." },
} as const;
